package org.apiman.client;

import java.io.UnsupportedEncodingException;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import org.apiman.client.util.GenericUtils;
import org.junit.BeforeClass;
import org.springframework.beans.factory.annotation.Value;

public abstract class ApimanServiceTestBase {

	@Value(value = "${apiman.url:http://localhost:8080/apiman}")
	protected String apimanUrl;
	
	protected static final int PAGE = 10;
	protected static final int COUNT = 20;
	protected static final String PAGE_AND_COUNT = "?page=" + PAGE + "&count=" + COUNT;

	protected static String downloadId = "download file";
	protected static String apiId = "my best api";
	protected static String clientId = "best client";
	protected static String version = "version 1.1";
	protected static String gatewayId = "gateway 1";
	protected static String organizationId = "organization 1";
	protected static String userId = "userId 1";
	protected static String apiDefinition = "";
	protected static String planId = "plan 1";
	protected static String policyId = "policy 1";
	protected static String contractId = "contract 1";
	protected static String roleId = "role 1";
	protected static String policyDefId = "policy Definition 1";
	protected static String pluginId = "plugin 1";

	protected static final String download = String.valueOf(true);
	protected static final Date FROM_DATE = new Date();
	protected static final Date TO_DATE = new Date();
	protected static final String FROM_TO_DATES = "?from="
			+ GenericUtils.formatDate(FROM_DATE != null ? FROM_DATE : new Date()) + "&to="
			+ GenericUtils.formatDate(TO_DATE != null ? TO_DATE : new Date());

	protected static final GenericUtils.INTERVAL INTERVAL_DAY = GenericUtils.INTERVAL.DAY;
	protected static final String INTERVAL = "interval=" + INTERVAL_DAY.toString().toLowerCase();

	protected static final Map<String, String> valuesMap = new HashMap<String, String>();
	protected static final Map<String, String> urlsMap = new HashMap<String, String>();

	protected static String GET_API_RESPONSE_STATISTICS_PER_CLIENT = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/metrics/clientResponseStats"
			+ FROM_TO_DATES;
	protected static String EXECUTE_ENTITY_ACTION = "/actions";
	protected static String GET_API_ORGANIZATIONS = "/currentuser/apiorgs";
	protected static String GET_CURRENT_USER_APIS = "/currentuser/apis";
	protected static String GET_CLIENT_ORGANIZATIONS = "/currentuser/clientorgs";
	protected static String GET_CURRENT_USER_CLIENTS = "/currentuser/clients";
	protected static String GET_CURRENT_USER_INFORMATION = "/currentuser/info";
	protected static String UPDATE_CURRENT_USER_INFORMATION = "/currentuser/info";
	protected static String GET_PLAN_ORGANIZATIONS = "/currentuser/planorgs";
	protected static String CREATE_ORGANIZATION = "/organizations";
	protected static String GET_ORGANIZATION_BY_ID = "/organizations/${organizationId}";
	protected static String UPDATE_ORGANIZATION = "/organizations/${organizationId}";
	protected static String DELETE_ORGANIZATION = "/organizations/${organizationId}";
	protected static String GET_ORGANIZATION_ACTIVITY = "/organizations/${organizationId}/activity" + PAGE_AND_COUNT;
	protected static String GET_API_VERSION_ACTIVITY = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/activity"
			+ PAGE_AND_COUNT;
	protected static String UPDATE_API_DEFINITION = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/definition";
	protected static String UPDATE_API_DEFINITION_FROM_URL = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/definition";
	protected static String REMOVE_API_DEFINITION = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/definition";
	protected static String RE_ORDER_API_POLICIES = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/reorderPolicies";
	protected static String GET_API_VERSION_STATUS = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/status";
	protected static String GET_API_USAGE_METRICS_PER_CLIENT = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/metrics/clientUsage"
			+ FROM_TO_DATES;
	protected static String GET_API_RESPONSE_STATISTICS_PER_PLAN = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/metrics/planResponseStats"
			+ FROM_TO_DATES;
	protected static String GET_API_USAGE_METRICS_PER_PLAN = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/metrics/planUsage"
			+ FROM_TO_DATES;
	protected static String GET_API_RESPONSE_STATISTICS = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/metrics/responseStats"
			+ FROM_TO_DATES;
	//protected static String GET_API_RESPONSE_STATISTICS_SUMMARY = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/metrics/summaryResponseStats"
	//		+ FROM_TO_DATES + "&" + INTERVAL;
	protected static String GET_API_USAGE_METRICS = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/metrics/usage"
			+ FROM_TO_DATES + "&" + INTERVAL;
	protected static String GET_API_POLICY_CHAIN = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/plans/${planId}/policyChain";
	protected static String DOWNLOAD_FILE = "/downloads/${downloadId}";
	protected static String LIST_ALL_GATEWAYS = "/gateways";
	protected static String TEST_GATEWAY = "/gateways";
	protected static String CREATE_GATEWAY = "/gateways";
	protected static String GET_GATEWAY_BY_ID = "/gateways/${gatewayId}";
	protected static String UPDATE_GATEWAY = "/gateways/${gatewayId}";
	protected static String DELETE_GATEWAY = "/gateways/${gatewayId}";
	protected static String LIST_APIS = "/organizations/${organizationId}/apis";
	protected static String CREATE_API = "/organizations/${organizationId}/apis";
	protected static String GET_API_BY_ID = "/organizations/${organizationId}/apis/${apiId}";
	protected static String UPDATE_API = "/organizations/${organizationId}/apis/${apiId}";
	protected static String DELETE_API = "/organizations/${organizationId}/apis/${apiId}";
	protected static String GET_API_ACTIVITY = "/organizations/${organizationId}/apis/${apiId}/activity" + PAGE_AND_COUNT;
	protected static String LIST_API_VERSIONS = "/organizations/${organizationId}/apis/${apiId}/versions";
	protected static String CREATE_API_VERSION = "/organizations/${organizationId}/apis/${apiId}/versions";
	protected static String GET_API_VERSION = "/organizations/${organizationId}/apis/${apiId}/versions/${version}";
	protected static String UPDATE_API_VERSION = "/organizations/${organizationId}/apis/${apiId}/versions/${version}";
	protected static String LIST_API_CONTRACTS = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/contracts" + PAGE_AND_COUNT;
	protected static String GET_API_DEFINITION = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/definition";
	protected static String GET_API_ENDPOINT = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/endpoint";
	protected static String LIST_API_PLANS = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/plans";
	protected static String ADD_API_POLICY = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/policies";
	protected static String GET_API_POLICY = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/policies/${policyId}";
	protected static String UPDATE_API_POLICY = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/policies/${policyId}";
	protected static String REMOVE_API_POLICY = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/policies/${policyId}";
	protected static String LIST_CLIENTS = "/organizations/${organizationId}/clients";
	protected static String CREATE_CLIENT = "/organizations/${organizationId}/clients";
	protected static String GET_CLIENT_BY_ID = "/organizations/${organizationId}/clients/${clientId}";
	protected static String UPDATE_CLIENT = "/organizations/${organizationId}/clients/${clientId}";
	protected static String DELETE_CLIENT = "/organizations/${organizationId}/clients/${clientId}";
	protected static String GET_CLIENT_VERSION = "/organizations/${organizationId}/clients/${clientId}/versions/${version}";
	protected static String GET_API_KEY = "/organizations/${organizationId}/clients/${clientId}/versions/${version}/apikey";
	protected static String UPDATE_API_KEY = "/organizations/${organizationId}/clients/${clientId}/versions/${version}/apikey";
	protected static String GET_API_CONTRACT = "/organizations/${organizationId}/clients/${clientId}/versions/${version}/contracts/${contractId}";
	protected static String BREAK_CONTRACT = "/organizations/${organizationId}/clients/${clientId}/versions/${version}/contracts/${contractId}";
	protected static String ADD_CLIENT_POLICY = "/organizations/${organizationId}/clients/${clientId}/versions/${version}/policies";
	protected static String GET_CLIENT_POLICY = "/organizations/${organizationId}/clients/${clientId}/versions/${version}/policies/${policyId}";
	protected static String LIST_PLANS = "/organizations/${organizationId}/plans";
	protected static String CREATE_PLAN = "/organizations/${organizationId}/plans";
	protected static String GET_PLAN_BY_ID = "/organizations/${organizationId}/plans/${planId}";
	protected static String UPDATE_PLAN = "/organizations/${organizationId}/plans/${planId}";
	protected static String DELETE_PLAN = "/organizations/${organizationId}/plans/${planId}";
	protected static String GET_PLAN_ACTIVITY = "/organizations/${organizationId}/plans/${planId}/activity" + PAGE_AND_COUNT;
	protected static String LIST_ALL_API_POLICIES = "/organizations/${organizationId}/apis/${apiId}/versions/${version}/policies";
	protected static String GET_CLIENT_ACTIVITY = "/organizations/${organizationId}/clients/${clientId}/activity"
			+ PAGE_AND_COUNT;
	protected static String LIST_CLIENT_VERSIONS = "/organizations/${organizationId}/clients/${clientId}/versions";
	protected static String CREATE_CLIENT_VERSION = "/organizations/${organizationId}/clients/${clientId}/versions";
	protected static String GET_CLIENT_VERSION_ACTIVITY = "/organizations/${organizationId}/clients/${clientId}/versions/${version}/activity"
			+ PAGE_AND_COUNT;
	protected static String GET_CLIENT_USAGE_METRICS_PER_API = "/organizations/${organizationId}/clients/${clientId}/versions/${version}/metrics/apiUsage"
			+ FROM_TO_DATES;
	protected static String REORDER_CLIENT_POLICIES = "/organizations/${organizationId}/clients/${clientId}/versions/${version}/reorderPolicies";
	protected static String GET_JSON_API_REGISTRY = "/organizations/${organizationId}/clients/${clientId}/versions/${version}/apiregistry/json?download=${download}";
	protected static String GET_XML_API_REGISTRY = "/organizations/${organizationId}/clients/${clientId}/versions/${version}/apiregistry/xml?download=${download}";
	protected static String LIST_ALL_CONTRACTS_FOR_CLIENT = "/organizations/${organizationId}/clients/${clientId}/versions/${version}/contracts";
	protected static String CREATE_API_CONTRACT = "/organizations/${organizationId}/clients/${clientId}/versions/${version}/contracts";
	protected static String BREAK_ALL_CONTRACTS = "/organizations/${organizationId}/clients/${clientId}/versions/${version}/contracts";
	protected static String LIST_ALL_CLIENT_POLICIES = "/organizations/${organizationId}/clients/${clientId}/versions/${version}/policies";
	protected static String UPDATE_CLIENT_POLICY = "/organizations/${organizationId}/clients/${clientId}/versions/${version}/policies/${policyId}";
	protected static String REMOVE_CLIENT_POLICY = "/organizations/${organizationId}/clients/${clientId}/versions/${version}/policies/${policyId}";
	protected static String LIST_ORGANIZATION_MEMBERS = "/organizations/${organizationId}/members";
	protected static String REVOKE_ALL_MEMBERSHIPS = "/organizations/${organizationId}/members/${userId}";
	protected static String CREATE_PLAN_VERSION = "/organizations/${organizationId}/plans/${planId}/versions";
	protected static String GET_PLAN_VERSION_ACTIVITY = "/organizations/${organizationId}/plans/${planId}/versions/${version}/activity"
			+ PAGE_AND_COUNT;
	protected static String REORDER_PLAN_POLICIES = "/organizations/${organizationId}/plans/${planId}/versions/${version}/reorderPolicies";
	protected static String LIST_ALL_PLAN_POLICIES = "/organizations/${organizationId}/plans/${planId}/versions/${version}/policies";
	protected static String REVOKE_SINGLE_MEMBERSHIP = "/organizations/${organizationId}/roles/${roleId}/${userId}";
	protected static String GET_CURRENT_USER_PERMISSIONS = "/permissions";
	protected static String GET_USER_PERMISSIONS = "/permissions/${userId}";
	protected static String LIST_AVAILABLE_PLUGINS = "/plugins/availablePlugins";
	protected static String GET_PLUGIN_POLICY_DEFINITIONS = "/plugins/${pluginId}/policyDefs";
	protected static String GET_PLUGIN_POLICY_FORM = "/plugins/${pluginId}/policyDefs/${policyDefId}/form";
	protected static String LIST_POLICY_DEFINITIONS = "/policyDefs";
	protected static String ADD_POLICY_DEFINITION = "/policyDefs";
	protected static String GET_POLICY_DEFINITION_BY_ID = "/policyDefs/${policyDefId}";
	protected static String UPDATE_POLICY_DEFINITION = "/policyDefs/${policyDefId}";
	protected static String DELETE_POLICY_DEFINITION = "/policyDefs/${policyDefId}";
	protected static String SEARCH_FOR_ORGANIZATIONS = "/search/organizations";
	protected static String SEARCH_FOR_APIS_IN_API_CATALOGUE = "/search/apiCatalog/entries";
	protected static String LIST_ALL_NAMESPACES_IN_API_CATALOGUE = "/search/apiCatalog/namespaces";
	protected static String LIST_USER_ORGANIZATIONS = "/users/${userId}/organizations";
	protected static String LIST_PLAN_VERSIONS = "/organizations/${organizationId}/plans/${planId}/versions";
	protected static String GET_PLAN_VERSION = "/organizations/${organizationId}/plans/${planId}/versions/${version}";
	protected static String ADD_PLAN_POLICY = "/organizations/${organizationId}/plans/${planId}/versions/${version}/policies";
	protected static String GET_PLAN_POLICY = "/organizations/${organizationId}/plans/${planId}/versions/${version}/policies/${policyId}";
	protected static String UPDATE_PLAN_POLICY = "/organizations/${organizationId}/plans/${planId}/versions/${version}/policies/${policyId}";
	protected static String REMOVE_PLAN_POLICY = "/organizations/${organizationId}/plans/${planId}/versions/${version}/policies/${policyId}";
	protected static String GRANT_MEMBERSHIP = "/organizations/${organizationId}/roles";
	protected static String LIST_ALL_PLUGINS = "/plugins";
	protected static String ADD_PLUGIN = "/plugins";
	protected static String GET_PLUGIN_BY_ID = "/plugins/${pluginId}";
	protected static String DELETE_PLUGIN_BY_ID = "/plugins/${pluginId}";
	protected static String LIST_ALL_ROLES = "/roles";
	protected static String CREATE_ROLE = "/roles";
	protected static String SEARCH_FOR_ROLES = "/roles/search";
	protected static String GET_ROLE_BY_ID = "/roles/${roleId}";
	protected static String UPDATE_ROLE_BY_ID = "/roles/${roleId}";
	protected static String DELETE_ROLE_BY_ID = "/roles/${roleId}";
	protected static String SEARCH_FOR_APIS = "/search/apis";
	protected static String SEARCH_FOR_CLIENTS = "/search/clients";
	protected static String EXPORT_DATA = "/system/export?download=${download}";
	protected static String IMPORT_DATA = "/system/import";
	protected static String GET_SYSTEM_STATUS = "/system/status";
	protected static String SEARCH_FOR_USERS = "/users/search";
	protected static String GET_USER_BY_ID = "/users/${userId}";
	protected static String UPDATE_USER_BY_ID = "/users/${userId}";
	protected static String GET_USER_ACTIVITY = "/users/${userId}/activity" + PAGE_AND_COUNT;
	protected static String LIST_USER_APIS = "/users/${userId}/apis";
	protected static String LIST_USER_CLIENTS = "/users/${userId}/clients";
	
	@BeforeClass
	public static void beforeClass() throws UnsupportedEncodingException {
		valuesMap.put("downloadId", downloadId);
		valuesMap.put("apiId", apiId);
		valuesMap.put("clientId", clientId);
		valuesMap.put("version", version);
		valuesMap.put("gatewayId", gatewayId);
		valuesMap.put("organizationId", organizationId);
		valuesMap.put("userId", userId);
		valuesMap.put("planId", planId);
		valuesMap.put("contractId", contractId);
		valuesMap.put("roleId", roleId);
		valuesMap.put("policyId", policyId);
		valuesMap.put("policyDefId", policyDefId);
		valuesMap.put("pluginId", pluginId);
		valuesMap.put("download", download);

		GenericUtils.encode(valuesMap);

		GET_API_RESPONSE_STATISTICS_PER_CLIENT = GenericUtils.substitute(GET_API_RESPONSE_STATISTICS_PER_CLIENT,
				valuesMap, false);
		EXECUTE_ENTITY_ACTION = GenericUtils.substitute(EXECUTE_ENTITY_ACTION, valuesMap, false);
		GET_API_ORGANIZATIONS = GenericUtils.substitute(GET_API_ORGANIZATIONS, valuesMap, false);
		GET_CURRENT_USER_APIS = GenericUtils.substitute(GET_CURRENT_USER_APIS, valuesMap, false);
		GET_CLIENT_ORGANIZATIONS = GenericUtils.substitute(GET_CLIENT_ORGANIZATIONS, valuesMap, false);
		GET_CURRENT_USER_CLIENTS = GenericUtils.substitute(GET_CURRENT_USER_CLIENTS, valuesMap, false);
		GET_CURRENT_USER_INFORMATION = GenericUtils.substitute(GET_CURRENT_USER_INFORMATION, valuesMap, false);
		UPDATE_CURRENT_USER_INFORMATION = GenericUtils.substitute(UPDATE_CURRENT_USER_INFORMATION, valuesMap, false);
		GET_PLAN_ORGANIZATIONS = GenericUtils.substitute(GET_PLAN_ORGANIZATIONS, valuesMap, false);
		CREATE_ORGANIZATION = GenericUtils.substitute(CREATE_ORGANIZATION, valuesMap, false);
		GET_ORGANIZATION_BY_ID = GenericUtils.substitute(GET_ORGANIZATION_BY_ID, valuesMap, false);
		UPDATE_ORGANIZATION = GenericUtils.substitute(UPDATE_ORGANIZATION, valuesMap, false);
		DELETE_ORGANIZATION = GenericUtils.substitute(DELETE_ORGANIZATION, valuesMap, false);
		GET_ORGANIZATION_ACTIVITY = GenericUtils.substitute(GET_ORGANIZATION_ACTIVITY, valuesMap, false);
		GET_API_VERSION_ACTIVITY = GenericUtils.substitute(GET_API_VERSION_ACTIVITY, valuesMap, false);
		UPDATE_API_DEFINITION = GenericUtils.substitute(UPDATE_API_DEFINITION, valuesMap, false);
		UPDATE_API_DEFINITION_FROM_URL = GenericUtils.substitute(UPDATE_API_DEFINITION_FROM_URL, valuesMap, false);
		REMOVE_API_DEFINITION = GenericUtils.substitute(REMOVE_API_DEFINITION, valuesMap, false);
		RE_ORDER_API_POLICIES = GenericUtils.substitute(RE_ORDER_API_POLICIES, valuesMap, false);
		GET_API_VERSION_STATUS = GenericUtils.substitute(GET_API_VERSION_STATUS, valuesMap, false);
		GET_API_USAGE_METRICS_PER_CLIENT = GenericUtils.substitute(GET_API_USAGE_METRICS_PER_CLIENT, valuesMap, false);
		GET_API_RESPONSE_STATISTICS_PER_PLAN = GenericUtils.substitute(GET_API_RESPONSE_STATISTICS_PER_PLAN, valuesMap,
				false);
		GET_API_USAGE_METRICS_PER_PLAN = GenericUtils.substitute(GET_API_USAGE_METRICS_PER_PLAN, valuesMap, false);
		GET_API_RESPONSE_STATISTICS = GenericUtils.substitute(GET_API_RESPONSE_STATISTICS, valuesMap, false);
		//GET_API_RESPONSE_STATISTICS_SUMMARY = GenericUtils.substitute(GET_API_RESPONSE_STATISTICS_SUMMARY, valuesMap,
		//		false);
		GET_API_USAGE_METRICS = GenericUtils.substitute(GET_API_USAGE_METRICS, valuesMap, false);
		GET_API_POLICY_CHAIN = GenericUtils.substitute(GET_API_POLICY_CHAIN, valuesMap, false);
		DOWNLOAD_FILE = GenericUtils.substitute(DOWNLOAD_FILE, valuesMap, false);
		LIST_ALL_GATEWAYS = GenericUtils.substitute(LIST_ALL_GATEWAYS, valuesMap, false);
		TEST_GATEWAY = GenericUtils.substitute(TEST_GATEWAY, valuesMap, false);
		CREATE_GATEWAY = GenericUtils.substitute(CREATE_GATEWAY, valuesMap, false);
		GET_GATEWAY_BY_ID = GenericUtils.substitute(GET_GATEWAY_BY_ID, valuesMap, false);
		UPDATE_GATEWAY = GenericUtils.substitute(UPDATE_GATEWAY, valuesMap, false);
		DELETE_GATEWAY = GenericUtils.substitute(DELETE_GATEWAY, valuesMap, false);
		LIST_APIS = GenericUtils.substitute(LIST_APIS, valuesMap, false);
		CREATE_API = GenericUtils.substitute(CREATE_API, valuesMap, false);
		GET_API_BY_ID = GenericUtils.substitute(GET_API_BY_ID, valuesMap, false);
		UPDATE_API = GenericUtils.substitute(UPDATE_API, valuesMap, false);
		DELETE_API = GenericUtils.substitute(DELETE_API, valuesMap, false);
		GET_API_ACTIVITY = GenericUtils.substitute(GET_API_ACTIVITY, valuesMap, false);
		LIST_API_VERSIONS = GenericUtils.substitute(LIST_API_VERSIONS, valuesMap, false);
		CREATE_API_VERSION = GenericUtils.substitute(CREATE_API_VERSION, valuesMap, false);
		GET_API_VERSION = GenericUtils.substitute(GET_API_VERSION, valuesMap, false);
		UPDATE_API_VERSION = GenericUtils.substitute(UPDATE_API_VERSION, valuesMap, false);
		LIST_API_CONTRACTS = GenericUtils.substitute(LIST_API_CONTRACTS, valuesMap, false);
		GET_API_DEFINITION = GenericUtils.substitute(GET_API_DEFINITION, valuesMap, false);
		GET_API_ENDPOINT = GenericUtils.substitute(GET_API_ENDPOINT, valuesMap, false);
		LIST_API_PLANS = GenericUtils.substitute(LIST_API_PLANS, valuesMap, false);
		ADD_API_POLICY = GenericUtils.substitute(ADD_API_POLICY, valuesMap, false);
		GET_API_POLICY = GenericUtils.substitute(GET_API_POLICY, valuesMap, false);
		UPDATE_API_POLICY = GenericUtils.substitute(UPDATE_API_POLICY, valuesMap, false);
		REMOVE_API_POLICY = GenericUtils.substitute(REMOVE_API_POLICY, valuesMap, false);
		LIST_CLIENTS = GenericUtils.substitute(LIST_CLIENTS, valuesMap, false);
		CREATE_CLIENT = GenericUtils.substitute(CREATE_CLIENT, valuesMap, false);
		GET_CLIENT_BY_ID = GenericUtils.substitute(GET_CLIENT_BY_ID, valuesMap, false);
		UPDATE_CLIENT = GenericUtils.substitute(UPDATE_CLIENT, valuesMap, false);
		DELETE_CLIENT = GenericUtils.substitute(DELETE_CLIENT, valuesMap, false);
		GET_CLIENT_VERSION = GenericUtils.substitute(GET_CLIENT_VERSION, valuesMap, false);
		GET_API_KEY = GenericUtils.substitute(GET_API_KEY, valuesMap, false);
		UPDATE_API_KEY = GenericUtils.substitute(UPDATE_API_KEY, valuesMap, false);
		GET_API_CONTRACT = GenericUtils.substitute(GET_API_CONTRACT, valuesMap, false);
		BREAK_CONTRACT = GenericUtils.substitute(BREAK_CONTRACT, valuesMap, false);
		ADD_CLIENT_POLICY = GenericUtils.substitute(ADD_CLIENT_POLICY, valuesMap, false);
		GET_CLIENT_POLICY = GenericUtils.substitute(GET_CLIENT_POLICY, valuesMap, false);
		LIST_PLANS = GenericUtils.substitute(LIST_PLANS, valuesMap, false);
		CREATE_PLAN = GenericUtils.substitute(CREATE_PLAN, valuesMap, false);
		GET_PLAN_BY_ID = GenericUtils.substitute(GET_PLAN_BY_ID, valuesMap, false);
		UPDATE_PLAN = GenericUtils.substitute(UPDATE_PLAN, valuesMap, false);
		DELETE_PLAN = GenericUtils.substitute(DELETE_PLAN, valuesMap, false);
		GET_PLAN_ACTIVITY = GenericUtils.substitute(GET_PLAN_ACTIVITY, valuesMap, false);
		LIST_ALL_API_POLICIES = GenericUtils.substitute(LIST_ALL_API_POLICIES, valuesMap, false);
		GET_CLIENT_ACTIVITY = GenericUtils.substitute(GET_CLIENT_ACTIVITY, valuesMap, false);
		LIST_CLIENT_VERSIONS = GenericUtils.substitute(LIST_CLIENT_VERSIONS, valuesMap, false);
		CREATE_CLIENT_VERSION = GenericUtils.substitute(CREATE_CLIENT_VERSION, valuesMap, false);
		GET_CLIENT_VERSION_ACTIVITY = GenericUtils.substitute(GET_CLIENT_VERSION_ACTIVITY, valuesMap, false);
		GET_CLIENT_USAGE_METRICS_PER_API = GenericUtils.substitute(GET_CLIENT_USAGE_METRICS_PER_API, valuesMap, false);
		REORDER_CLIENT_POLICIES = GenericUtils.substitute(REORDER_CLIENT_POLICIES, valuesMap, false);
		GET_JSON_API_REGISTRY = GenericUtils.substitute(GET_JSON_API_REGISTRY, valuesMap, false);
		GET_XML_API_REGISTRY = GenericUtils.substitute(GET_XML_API_REGISTRY, valuesMap, false);
		LIST_ALL_CONTRACTS_FOR_CLIENT = GenericUtils.substitute(LIST_ALL_CONTRACTS_FOR_CLIENT, valuesMap, false);
		CREATE_API_CONTRACT = GenericUtils.substitute(CREATE_API_CONTRACT, valuesMap, false);
		BREAK_ALL_CONTRACTS = GenericUtils.substitute(BREAK_ALL_CONTRACTS, valuesMap, false);
		LIST_ALL_CLIENT_POLICIES = GenericUtils.substitute(LIST_ALL_CLIENT_POLICIES, valuesMap, false);
		UPDATE_CLIENT_POLICY = GenericUtils.substitute(UPDATE_CLIENT_POLICY, valuesMap, false);
		REMOVE_CLIENT_POLICY = GenericUtils.substitute(REMOVE_CLIENT_POLICY, valuesMap, false);
		LIST_ORGANIZATION_MEMBERS = GenericUtils.substitute(LIST_ORGANIZATION_MEMBERS, valuesMap, false);
		REVOKE_ALL_MEMBERSHIPS = GenericUtils.substitute(REVOKE_ALL_MEMBERSHIPS, valuesMap, false);
		CREATE_PLAN_VERSION = GenericUtils.substitute(CREATE_PLAN_VERSION, valuesMap, false);
		GET_PLAN_VERSION_ACTIVITY = GenericUtils.substitute(GET_PLAN_VERSION_ACTIVITY, valuesMap, false);
		REORDER_PLAN_POLICIES = GenericUtils.substitute(REORDER_PLAN_POLICIES, valuesMap, false);
		LIST_ALL_PLAN_POLICIES = GenericUtils.substitute(LIST_ALL_PLAN_POLICIES, valuesMap, false);
		REVOKE_SINGLE_MEMBERSHIP = GenericUtils.substitute(REVOKE_SINGLE_MEMBERSHIP, valuesMap, false);
		GET_CURRENT_USER_PERMISSIONS = GenericUtils.substitute(GET_CURRENT_USER_PERMISSIONS, valuesMap, false);
		GET_USER_PERMISSIONS = GenericUtils.substitute(GET_USER_PERMISSIONS, valuesMap, false);
		LIST_AVAILABLE_PLUGINS = GenericUtils.substitute(LIST_AVAILABLE_PLUGINS, valuesMap, false);
		GET_PLUGIN_POLICY_DEFINITIONS = GenericUtils.substitute(GET_PLUGIN_POLICY_DEFINITIONS, valuesMap, false);
		GET_PLUGIN_POLICY_FORM = GenericUtils.substitute(GET_PLUGIN_POLICY_FORM, valuesMap, false);
		LIST_POLICY_DEFINITIONS = GenericUtils.substitute(LIST_POLICY_DEFINITIONS, valuesMap, false);
		ADD_POLICY_DEFINITION = GenericUtils.substitute(ADD_POLICY_DEFINITION, valuesMap, false);
		GET_POLICY_DEFINITION_BY_ID = GenericUtils.substitute(GET_POLICY_DEFINITION_BY_ID, valuesMap, false);
		UPDATE_POLICY_DEFINITION = GenericUtils.substitute(UPDATE_POLICY_DEFINITION, valuesMap, false);
		DELETE_POLICY_DEFINITION = GenericUtils.substitute(DELETE_POLICY_DEFINITION, valuesMap, false);
		SEARCH_FOR_ORGANIZATIONS = GenericUtils.substitute(SEARCH_FOR_ORGANIZATIONS, valuesMap, false);
		SEARCH_FOR_APIS_IN_API_CATALOGUE = GenericUtils.substitute(SEARCH_FOR_APIS_IN_API_CATALOGUE, valuesMap, false);
		LIST_ALL_NAMESPACES_IN_API_CATALOGUE = GenericUtils.substitute(LIST_ALL_NAMESPACES_IN_API_CATALOGUE, valuesMap,
				false);
		LIST_USER_ORGANIZATIONS = GenericUtils.substitute(LIST_USER_ORGANIZATIONS, valuesMap, false);
		LIST_PLAN_VERSIONS = GenericUtils.substitute(LIST_PLAN_VERSIONS, valuesMap, false);
		GET_PLAN_VERSION = GenericUtils.substitute(GET_PLAN_VERSION, valuesMap, false);
		ADD_PLAN_POLICY = GenericUtils.substitute(ADD_PLAN_POLICY, valuesMap, false);
		GET_PLAN_POLICY = GenericUtils.substitute(GET_PLAN_POLICY, valuesMap, false);
		UPDATE_PLAN_POLICY = GenericUtils.substitute(UPDATE_PLAN_POLICY, valuesMap, false);
		REMOVE_PLAN_POLICY = GenericUtils.substitute(REMOVE_PLAN_POLICY, valuesMap, false);
		GRANT_MEMBERSHIP = GenericUtils.substitute(GRANT_MEMBERSHIP, valuesMap, false);
		LIST_ALL_PLUGINS = GenericUtils.substitute(LIST_ALL_PLUGINS, valuesMap, false);
		ADD_PLUGIN = GenericUtils.substitute(ADD_PLUGIN, valuesMap, false);
		GET_PLUGIN_BY_ID = GenericUtils.substitute(GET_PLUGIN_BY_ID, valuesMap, false);
		DELETE_PLUGIN_BY_ID = GenericUtils.substitute(DELETE_PLUGIN_BY_ID, valuesMap, false);
		LIST_ALL_ROLES = GenericUtils.substitute(LIST_ALL_ROLES, valuesMap, false);
		CREATE_ROLE = GenericUtils.substitute(CREATE_ROLE, valuesMap, false);
		SEARCH_FOR_ROLES = GenericUtils.substitute(SEARCH_FOR_ROLES, valuesMap, false);
		GET_ROLE_BY_ID = GenericUtils.substitute(GET_ROLE_BY_ID, valuesMap, false);
		UPDATE_ROLE_BY_ID = GenericUtils.substitute(UPDATE_ROLE_BY_ID, valuesMap, false);
		DELETE_ROLE_BY_ID = GenericUtils.substitute(DELETE_ROLE_BY_ID, valuesMap, false);
		SEARCH_FOR_APIS = GenericUtils.substitute(SEARCH_FOR_APIS, valuesMap, false);
		SEARCH_FOR_CLIENTS = GenericUtils.substitute(SEARCH_FOR_CLIENTS, valuesMap, false);
		EXPORT_DATA = GenericUtils.substitute(EXPORT_DATA, valuesMap, false);
		IMPORT_DATA = GenericUtils.substitute(IMPORT_DATA, valuesMap, false);
		GET_SYSTEM_STATUS = GenericUtils.substitute(GET_SYSTEM_STATUS, valuesMap, false);
		SEARCH_FOR_USERS = GenericUtils.substitute(SEARCH_FOR_USERS, valuesMap, false);
		GET_USER_BY_ID = GenericUtils.substitute(GET_USER_BY_ID, valuesMap, false);
		UPDATE_USER_BY_ID = GenericUtils.substitute(UPDATE_USER_BY_ID, valuesMap, false);
		GET_USER_ACTIVITY = GenericUtils.substitute(GET_USER_ACTIVITY, valuesMap, false);
		LIST_USER_APIS = GenericUtils.substitute(LIST_USER_APIS, valuesMap, false);
		LIST_USER_CLIENTS = GenericUtils.substitute(LIST_USER_CLIENTS, valuesMap, false);

		urlsMap.put("getApiResponseStatisticsPerClient", GET_API_RESPONSE_STATISTICS_PER_CLIENT);
		urlsMap.put("downloadFile", DOWNLOAD_FILE);
		urlsMap.put("listAllGateways", LIST_ALL_GATEWAYS);
		urlsMap.put("testGateway", TEST_GATEWAY);
		urlsMap.put("createGateway", CREATE_GATEWAY);
		urlsMap.put("getGatewayById", GET_GATEWAY_BY_ID);
		urlsMap.put("executeEntityAction", EXECUTE_ENTITY_ACTION);
		urlsMap.put("getApiOrganizations", GET_API_ORGANIZATIONS);
		urlsMap.put("getCurrentUserApis", GET_CURRENT_USER_APIS);
		urlsMap.put("getClientOrganizations", GET_CLIENT_ORGANIZATIONS);
		urlsMap.put("getCurrentUserClients", GET_CURRENT_USER_CLIENTS);
		urlsMap.put("getCurrentUserInformation", GET_CURRENT_USER_INFORMATION);
		urlsMap.put("updateCurrentUserInformation", UPDATE_CURRENT_USER_INFORMATION);
		urlsMap.put("getPlanOrganizations", GET_PLAN_ORGANIZATIONS);
		urlsMap.put("createOrganization", CREATE_ORGANIZATION);
		urlsMap.put("getOrganizationById", GET_ORGANIZATION_BY_ID);
		urlsMap.put("updateOrganization", UPDATE_ORGANIZATION);
		urlsMap.put("deleteOrganization", DELETE_ORGANIZATION);
		urlsMap.put("getOrganizationActivity", GET_ORGANIZATION_ACTIVITY);
		urlsMap.put("getApiVersionActivity", GET_API_VERSION_ACTIVITY);
		urlsMap.put("updateApiDefinition", UPDATE_API_DEFINITION);
		urlsMap.put("updateApiDefinitionFromUrl", UPDATE_API_DEFINITION_FROM_URL);
		urlsMap.put("removeApiDefinition", REMOVE_API_DEFINITION);
		urlsMap.put("reOrderApiPolicies", RE_ORDER_API_POLICIES);
		urlsMap.put("getApiVersionStatus", GET_API_VERSION_STATUS);
		urlsMap.put("getApiUsageMetricsPerClient", GET_API_USAGE_METRICS_PER_CLIENT);
		urlsMap.put("getApiResponseStatisticsPerPlan", GET_API_RESPONSE_STATISTICS_PER_PLAN);
		urlsMap.put("getApiUsageMetricsPerPlan", GET_API_USAGE_METRICS_PER_PLAN);
		urlsMap.put("getApiResponseStatistics", GET_API_RESPONSE_STATISTICS);
		//urlsMap.put("getApiResponseStatisticsSummary", GET_API_RESPONSE_STATISTICS_SUMMARY);
		urlsMap.put("getApiUsageMetrics", GET_API_USAGE_METRICS);
		urlsMap.put("getApiPolicyChain", GET_API_POLICY_CHAIN);
		urlsMap.put("listAllApiPolicies", LIST_ALL_API_POLICIES);
		urlsMap.put("getClientActivity", GET_CLIENT_ACTIVITY);
		urlsMap.put("listClientVersions", LIST_CLIENT_VERSIONS);
		urlsMap.put("createClientVersion", CREATE_CLIENT_VERSION);
		urlsMap.put("getClientVersionActivity", GET_CLIENT_VERSION_ACTIVITY);
		urlsMap.put("getClientUsageMetricsPerApi", GET_CLIENT_USAGE_METRICS_PER_API);
		urlsMap.put("reorderClientPolicies", REORDER_CLIENT_POLICIES);
		urlsMap.put("getJsonApiRegistry", GET_JSON_API_REGISTRY);
		urlsMap.put("getXmlApiRegistry", GET_XML_API_REGISTRY);
		urlsMap.put("listAllContractsForClient", LIST_ALL_CONTRACTS_FOR_CLIENT);
		urlsMap.put("createApiContract", CREATE_API_CONTRACT);
		urlsMap.put("breakAllContracts", BREAK_ALL_CONTRACTS);
		urlsMap.put("listAllClientPolicies", LIST_ALL_CLIENT_POLICIES);
		urlsMap.put("updateClientPolicy", UPDATE_CLIENT_POLICY);
		urlsMap.put("updateGateway", UPDATE_GATEWAY);
		urlsMap.put("deleteGateway", DELETE_GATEWAY);
		urlsMap.put("listApis", LIST_APIS);
		urlsMap.put("createApi", CREATE_API);
		urlsMap.put("getApiById", GET_API_BY_ID);
		urlsMap.put("updateApi", UPDATE_API);
		urlsMap.put("deleteApi", DELETE_API);
		urlsMap.put("getApiActivity", GET_API_ACTIVITY);
		urlsMap.put("listApiVersions", LIST_API_VERSIONS);
		urlsMap.put("createApiVersion", CREATE_API_VERSION);
		urlsMap.put("getApiVersion", GET_API_VERSION);
		urlsMap.put("updateApiVersion", UPDATE_API_VERSION);
		urlsMap.put("listApiContracts", LIST_API_CONTRACTS);
		urlsMap.put("getApiDefinition", GET_API_DEFINITION);
		urlsMap.put("getApiEndpoint", GET_API_ENDPOINT);
		urlsMap.put("listApiPlans", LIST_API_PLANS);
		urlsMap.put("addApiPolicy", ADD_API_POLICY);
		urlsMap.put("getApiPolicy", GET_API_POLICY);
		urlsMap.put("updateApiPolicy", UPDATE_API_POLICY);
		urlsMap.put("removeApiPolicy", REMOVE_API_POLICY);
		urlsMap.put("listClients", LIST_CLIENTS);
		urlsMap.put("createClient", CREATE_CLIENT);
		urlsMap.put("getClientById", GET_CLIENT_BY_ID);
		urlsMap.put("updateClient", UPDATE_CLIENT);
		urlsMap.put("deleteClient", DELETE_CLIENT);
		urlsMap.put("getClientVersion", GET_CLIENT_VERSION);
		urlsMap.put("getApiKey", GET_API_KEY);
		urlsMap.put("updateApiKey", UPDATE_API_KEY);
		urlsMap.put("getApiContract", GET_API_CONTRACT);
		urlsMap.put("breakContract", BREAK_CONTRACT);
		urlsMap.put("addClientPolicy", ADD_CLIENT_POLICY);
		urlsMap.put("getClientPolicy", GET_CLIENT_POLICY);
		urlsMap.put("listPlans", LIST_PLANS);
		urlsMap.put("createPlan", CREATE_PLAN);
		urlsMap.put("getPlanById", GET_PLAN_BY_ID);
		urlsMap.put("updatePlan", UPDATE_PLAN);
		urlsMap.put("deletePlan", DELETE_PLAN);
		urlsMap.put("getPlanActivity", GET_PLAN_ACTIVITY);
		urlsMap.put("listPlanVersions", LIST_PLAN_VERSIONS);
		urlsMap.put("getPlanVersion", GET_PLAN_VERSION);
		urlsMap.put("addPlanPolicy", ADD_PLAN_POLICY);
		urlsMap.put("getPlanPolicy", GET_PLAN_POLICY);
		urlsMap.put("updatePlanPolicy", UPDATE_PLAN_POLICY);
		urlsMap.put("removePlanPolicy", REMOVE_PLAN_POLICY);
		urlsMap.put("grantMembership", GRANT_MEMBERSHIP);
		urlsMap.put("listAllPlugins", LIST_ALL_PLUGINS);
		urlsMap.put("addPlugin", ADD_PLUGIN);
		urlsMap.put("getPluginById", GET_PLUGIN_BY_ID);
		urlsMap.put("deletePluginById", DELETE_PLUGIN_BY_ID);
		urlsMap.put("listAllRoles", LIST_ALL_ROLES);
		urlsMap.put("createRole", CREATE_ROLE);
		urlsMap.put("searchForRoles", SEARCH_FOR_ROLES);
		urlsMap.put("getRoleById", GET_ROLE_BY_ID);
		urlsMap.put("updateRoleById", UPDATE_ROLE_BY_ID);
		urlsMap.put("deleteRoleById", DELETE_ROLE_BY_ID);
		urlsMap.put("searchForApis", SEARCH_FOR_APIS);
		urlsMap.put("searchForClients", SEARCH_FOR_CLIENTS);
		urlsMap.put("exportData", EXPORT_DATA);
		urlsMap.put("importData", IMPORT_DATA);
		urlsMap.put("getSystemStatus", GET_SYSTEM_STATUS);
		urlsMap.put("searchForUsers", SEARCH_FOR_USERS);
		urlsMap.put("removeClientPolicy", REMOVE_CLIENT_POLICY);
		urlsMap.put("listOrganizationMembers", LIST_ORGANIZATION_MEMBERS);
		urlsMap.put("revokeAllMemberships", REVOKE_ALL_MEMBERSHIPS);
		urlsMap.put("createPlanVersion", CREATE_PLAN_VERSION);
		urlsMap.put("getPlanVersionActivity", GET_PLAN_VERSION_ACTIVITY);
		urlsMap.put("reorderPlanPolicies", REORDER_PLAN_POLICIES);
		urlsMap.put("listAllPlanPolicies", LIST_ALL_PLAN_POLICIES);
		urlsMap.put("revokeSingleMembership", REVOKE_SINGLE_MEMBERSHIP);
		urlsMap.put("getCurrentUserPermissions", GET_CURRENT_USER_PERMISSIONS);
		urlsMap.put("getUserPermissions", GET_USER_PERMISSIONS);
		urlsMap.put("listAvailablePlugins", LIST_AVAILABLE_PLUGINS);
		urlsMap.put("getPluginPolicyDefinitions", GET_PLUGIN_POLICY_DEFINITIONS);
		urlsMap.put("getPluginPolicyForm", GET_PLUGIN_POLICY_FORM);
		urlsMap.put("listPolicyDefinitions", LIST_POLICY_DEFINITIONS);
		urlsMap.put("addPolicyDefinition", ADD_POLICY_DEFINITION);
		urlsMap.put("getPolicyDefinitionById", GET_POLICY_DEFINITION_BY_ID);
		urlsMap.put("updatePolicyDefinition", UPDATE_POLICY_DEFINITION);
		urlsMap.put("deletePolicyDefinition", DELETE_POLICY_DEFINITION);
		urlsMap.put("searchForOrganizations", SEARCH_FOR_ORGANIZATIONS);
		urlsMap.put("searchForApisInApiCatalogue", SEARCH_FOR_APIS_IN_API_CATALOGUE);
		urlsMap.put("listAllNamespacesInApiCatalogue", LIST_ALL_NAMESPACES_IN_API_CATALOGUE);
		urlsMap.put("listUserOrganizations", LIST_USER_ORGANIZATIONS);
		urlsMap.put("getUserById", GET_USER_BY_ID);
		urlsMap.put("updateUserById", UPDATE_USER_BY_ID);
		urlsMap.put("getUserActivity", GET_USER_ACTIVITY);
		urlsMap.put("listUserApis", LIST_USER_APIS);
		urlsMap.put("listUserClients", LIST_USER_CLIENTS);
	}
}
