package org.apiman.client.resources;

import org.apiman.client.ApiClient;
import org.springframework.stereotype.Component;

@Component
public class DownloadsClient extends ApiClient {
	
	private static final String DOWNLOADS_PATH = "/downloads";
	
	/* This endpoint is used to download a file that was previously generated by some other REST API call. For example, 
	 * when exporting data via the /system/export endpoint, a temporary download link may be created. This represents that 
	 * temporary download link. In this example, the download will result in the exported data.
	 */
	public String downloadFile() {
		
		return apimanUrl;
	}
}
