package org.apiman.client.resources;

import static org.apiman.client.util.GenericUtils.buildURL;
import static org.apiman.client.util.GenericUtils.substitute;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apiman.client.AbstractApimanClient;
import org.apiman.client.domain.plugin.NewPlugin;
import org.apiman.client.domain.plugin.Plugin;
import org.apiman.client.domain.plugin.PluginSummary;
import org.apiman.client.resources.plugins.IPluginsPolicyDefsClient;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestTemplate;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString
@EqualsAndHashCode(callSuper=false)
@Component
@Getter(value = AccessLevel.PUBLIC)
@Setter(value = AccessLevel.PRIVATE)
public class PluginsClientImpl extends AbstractApimanClient implements IPluginsClient {
	
	@Autowired
	@Qualifier("redhatApimanAdminRestClient")
	protected RestTemplate adminTemplate;
	
	@Autowired
	private IPluginsPolicyDefsClient pluginsPolicyDefsClient;
	
	private static final String AVAILABLE_PLUGINS_PATH = "/availablePlugins";
	
	/* This endpoint returns a list of all plugins that have been added to the system.
	 * 
	 */
	@Override
	public List<PluginSummary> listAllPlugins() {
		
		String url = buildURL(apimanUrl, PLUGINS_PATH);
		PluginSummary[] plugins = restTemplate.getForObject(url, PluginSummary[].class);
		
		return plugins != null ? Arrays.asList(plugins) : null;
	}
	
	/* Use this endpoint to add a plugin to apiman. A plugin consists of the maven coordinates of an artifact deployed 
	 * to a remote maven repository (e.g. maven central).
	 */
	@Override
	public Plugin addPlugin(NewPlugin plugin) {
		
		String url = buildURL(apimanUrl, PLUGINS_PATH);
		return adminTemplate.postForObject(url, plugin, Plugin.class);
	}
	
	/* Use this endpoint to retrieve a list of all plugins available to be installed. This list is generated by 
	 * querying all of the plugin registries configured in apiman and returning the list of plugins found in each (sorted by name). 
	 * Note that this endpoint includes all plugins, even those already installed.
	 */
	@Override
	public List<PluginSummary> listAvailablePlugins() {
		
		String url = buildURL(apimanUrl, PLUGINS_PATH, AVAILABLE_PLUGINS_PATH);
		PluginSummary[] plugins = restTemplate.getForObject(url, PluginSummary[].class);
		
		return plugins != null ? Arrays.asList(plugins) : null;
	}
	
	/* This endpoint can be used to access the full information about an apiman plugin. The plugin is retrieved using the ID 
	 * it was given when it was added. The ID information can be retrieved by listing all plugins or remembered when a plugin is first added.
	 */
	@Override
	public Plugin getPluginById(String pluginId) {
		
		String url = buildURL(apimanUrl, PLUGINS_PATH, "/${pluginId}");
		Map<String, String> map = new HashMap<>();
		map.put("pluginId", pluginId);
		url = substitute(url, map, true);
		
		return adminTemplate.getForObject(url, Plugin.class);
	}
	
	/* Call this endpoint to delete a plugin.
	 * 
	 */
	@Override
	public void deletePluginById(String pluginId) {
		
		String url = buildURL(apimanUrl, PLUGINS_PATH, "/${pluginId}");
		Map<String, String> map = new HashMap<>();
		map.put("pluginId", pluginId);
		url = substitute(url, map, true);
		
		adminTemplate.delete(url);
	}
}
